spring:
    data:
        mongodb:
            uri: mongodb://localhost:27017/spring-security

springdoc:
    api-docs:
        enabled: true
        groups:
            enabled: true
    swagger-ui:
        enabled: true
        path: /
        tags-sorter: alpha
        operations-sorter: method
        display-request-duration: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
        enabled: true
    info:
        enabled: true